// Generated from the product photo library. Category and subcategory copy is editable — category/subcategory background images are Unsplash ids (product photos stay on Cloudinary).
import type { Category } from "./store";

export const catalog: Category[] = [
  {
    slug: "office", name: "Office Furniture", short: "Office", image: "1431540015161-0bf868a2d407",
    description: "Executive and ergonomic chairs, desks, workstations, meeting tables, reception counters and storage — built for daily commercial use.",
    subcategories: [
      { slug: "executive-chairs", name: "Executive Chairs", image: "1612372606404-0ab33e7187ee", blurb: "High-back executive seating in leather and mesh, with headrests and adjustable arms for long hours at the desk.", features: ["High back with headrest options","Adjustable armrests and tilt","Gas-lift height adjustment","Heavy-duty base on smooth castors"], specs: {"Back":"Mesh / leather","Arms":"Adjustable","Base":"Nylon / chrome","Adjustment":"Height & tilt"}, colors: ["Black","White","Grey"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862142/products/dxwdscxrsa8liksqovca.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862142/products/nlrrxyt2tnvzi0vsox2a.jpg"] },
      { slug: "manager-chairs", name: "Manager Chairs", image: "1580480055273-228ff5388ef8", blurb: "Mid and high-back manager chairs that look sharp in a cabin and stay comfortable all day.", features: ["Breathable mesh or fabric back","Padded seat with lumbar curve","Height and tilt adjustment","Smooth-rolling castors"], specs: {"Back":"Mesh / fabric","Seat":"Padded foam","Base":"Nylon / chrome","Adjustment":"Height & tilt"}, colors: ["Black","Orange","White","Navy"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862146/products/lnryr2elj2clt5ynrcze.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862146/products/atjsr0lan2nieklzsrf3.jpg"] },
      { slug: "computer-chairs", name: "Computer Chairs", image: "1572521165329-b197f9ea3da6", blurb: "Everyday task chairs for desks, call centres and home offices — light, breathable and easy to adjust.", features: ["Ventilated mesh back","Height-adjustable gas lift","360° swivel","Comfortable padded seat"], specs: {"Back":"Mesh","Seat":"Foam / fabric","Base":"Nylon","Swivel":"360°"}, colors: ["Black","White","Grey","Blue"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862140/products/reyt9io2h1doaaufxdzl.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862140/products/b8kqot0psyxgjewtt9dc.jpg"] },
      { slug: "visitor-chairs", name: "Visitor Chairs", image: "1598300042247-d088f8ab3a91", blurb: "Cantilever and four-leg guest chairs for cabins, meeting rooms and reception areas.", features: ["Cantilever or fixed frames","Mesh, fabric or leather","Padded seat and armrests","Stable steel frame"], specs: {"Frame":"Chrome / powder-coated steel","Seat":"Foam padded","Upholstery":"Mesh / leather / fabric"}, colors: ["Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862147/products/jpadhztund5tri4nhxyj.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862147/products/dpjbfr51ikyucouua4bz.jpg"] },
      { slug: "office-sofas", name: "Office Sofas", image: "1540574163026-643ea20ade25", blurb: "Reception and executive-cabin sofa sets in leather, leatherette and velvet.", features: ["Hardwood frame","High-density foam cushions","Sets of 3+1+1 or 2-seaters","Easy-clean upholstery"], specs: {"Frame":"Hardwood","Foam":"High density","Upholstery":"Leather / velvet","Seating":"1 – 3 seaters"}, colors: ["Black","Navy","Brown"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862148/products/a31drv4dp61lwsutjusr.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862148/products/gptw4q6nagow9ve45bsm.jpg"], madeToOrder: true },
      { slug: "executive-tables", name: "Executive Tables", image: "1593062096033-9a26b09da705", blurb: "Statement desks with generous work surfaces, side returns and built-in storage for the corner office.", features: ["Large scratch-resistant top","Side return and storage options","Cable management","Custom sizes available"], specs: {"Top":"Laminate / veneer","Frame":"Steel / MDF","Storage":"Drawers / side cabinet","Finish":"Walnut / oak / black"}, colors: ["Black","Walnut","Grey"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862150/products/rgwj4gukwiztflcqyz50.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862150/products/tnajslfze0wslvl8mbxa.jpg"], madeToOrder: true },
      { slug: "manager-tables", name: "Manager Tables", image: "1596079890744-c1a0462d0975", blurb: "Practical manager desks with side cabinets and shelves for a tidy, productive cabin.", features: ["Integrated side storage","Durable laminate top","Sturdy steel or panel legs","Cable cut-outs"], specs: {"Top":"Laminate","Frame":"Steel / MDF","Storage":"Cabinet / shelf","Finish":"Teak / walnut / white"}, colors: ["Grey","Teak","Walnut","White"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862152/products/jz8g9ryrydyo5teptxkf.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862153/products/e6fawuixve18yyrmj2dg.jpg"], madeToOrder: true },
      { slug: "meeting-tables", name: "Meeting Tables", image: "1517502884422-41eaead166d4", blurb: "Conference and boardroom tables for small huddles up to large teams, with cable ports for power and data.", features: ["Seats 4 to 20 people","Cable ports for power and data","Rectangular, round and oval shapes","Sturdy metal or panel bases"], specs: {"Top":"Laminate / veneer","Base":"Steel / panel","Shapes":"Rectangular / round / oval","Seats":"4 – 20"}, colors: ["Black","Grey","Mahogany","Oak"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862153/products/wnc9vxhtl7rnyq9hmugn.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862153/products/ulxjpoftruimeznv9ras.jpg"], madeToOrder: true },
      { slug: "reception-tables", name: "Reception Tables", image: "1634712282287-14ed57b9cc89", blurb: "Front-desk counters that give clients a confident first impression.", features: ["Two-level counter top","Integrated storage and cable access","LED accent options","Built to your layout"], specs: {"Top":"Laminate / veneer","Finish":"Oak / white / black","Lighting":"LED optional","Sizes":"Made to measure"}, colors: ["White","Black","Oak"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862154/products/fgzowylwkqasvz239txb.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862154/products/lbjuzb8bndbhjh4eeoue.jpg"], madeToOrder: true },
      { slug: "laptop-tables", name: "Laptop Tables", image: "1497215842964-222b430dc094", blurb: "Compact laptop desks and sofa-side tables that move where you work.", features: ["Height-adjustable options","Castors for easy moving","Slim, space-saving frame","Quick assembly"], specs: {"Top":"Laminate / MDF","Frame":"Powder-coated steel","Height":"Adjustable / fixed"}, colors: ["Oak","Black","White"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862152/products/g1vy5dqu7mncwzv1unza.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862152/products/undfdyr5gxgp4hgxrw1b.jpg"] },
      { slug: "workstations", name: "Workstations", image: "1497366811353-6870744d04b2", blurb: "Modular desking for teams of every size — linear, cluster and L-shaped layouts with privacy screens.", features: ["Add seats as your team grows","Privacy screens and partitions","Mobile pedestals with locks","Free space planning"], specs: {"Top":"Laminate","Frame":"Powder-coated steel","Screens":"Fabric / acrylic","Layouts":"Linear / cluster / L-shape"}, colors: ["White","Walnut","Red","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862155/products/ufgbcw804euvi91dvymq.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862155/products/bdnux706ft8uaay3mthr.jpg"], madeToOrder: true },
      { slug: "office-storage", name: "Office Storage", image: "1558997519-83ea9252edf8", blurb: "Back cabinets, filing units and side racks that keep documents organised and out of sight.", features: ["Lockable doors and drawers","Adjustable internal shelves","Matches desk finishes","Custom sizes available"], specs: {"Material":"MDF / laminate","Finish":"Walnut / teak / black","Lock":"Central locking"}, colors: ["Walnut","Oak","Grey","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862149/products/qfb0vj5v3fyh66ehck3y.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862149/products/p9h2pisja2uunn8qoeto.jpg"], madeToOrder: true },
    ],
  },
  {
    slug: "study", name: "Study Furniture", short: "Study", image: "1600494603989-9650cf6ddd3d",
    description: "Study tables, student and gaming chairs, gaming desks and corner shelves for homes, hostels and students' rooms.",
    subcategories: [
      { slug: "study-tables", name: "Study Tables", image: "1611269154421-4e27233ac5c7", blurb: "Study and computer desks in oak, walnut and white — with shelves, drawers and sturdy steel frames.", features: ["Sturdy steel frame","Scratch-resistant desktop","Open shelves or drawers","Easy flat-pack assembly"], specs: {"Top":"Laminated board","Frame":"Powder-coated steel","Storage":"Shelf / drawers","Finish":"Oak / walnut / white / black"}, colors: ["Oak","White","Black","Walnut"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862136/products/yfwkn1muxwrxlxqaupvl.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862163/products/troxhqo1ffutuz2jpiob.jpg"] },
      { slug: "study-chairs", name: "Study Chairs", image: "1611464908623-07f19927264e", blurb: "Supportive chairs for long study sessions — mesh back office chairs and chairs with writing pads.", features: ["Breathable mesh or padded seat","Height adjustable options","Compact footprint","Writing-pad versions available"], specs: {"Frame":"Steel / nylon","Seat":"Padded","Adjustment":"Height / fixed"}, colors: ["Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862161/products/vww05sajcswottzkdxck.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862161/products/cj1nolzwklgmrwifk6w2.jpg"] },
      { slug: "gaming-chairs", name: "Gaming Chairs", image: "1518455027359-f3f8164ba6bd", blurb: "Racing-style gaming chairs with headrest and lumbar cushions, adjustable arms and recline.", features: ["Adjustable recline","Head and lumbar cushions","4D armrests","Footrest on selected models"], specs: {"Cover":"PU leather","Arms":"Adjustable","Recline":"Up to 180°","Base":"Nylon / metal"}, colors: ["Black","Blue","Red"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862160/products/dk2hwwa81nl6gk5lyfrv.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862160/products/rnobhcq5kpn6g4qzpsnj.jpg"] },
      { slug: "gaming-tables", name: "Gaming Tables", image: "1564069114553-7215e1ff1890", blurb: "Gaming desks with cable management, cup holder and headset hook.", features: ["Large carbon-style surface","Cup holder and headset hook","Cable management","Z, K and L-shaped frames"], specs: {"Top":"Carbon-finish board","Frame":"Powder-coated steel","Shapes":"Straight / L-shaped"}, colors: ["Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862162/products/nwsltadatuzz0gjzp1bi.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862163/products/o2xbyigjatrmsupdo0a6.jpg"] },
      { slug: "corner-storages", name: "Corner Shelves", image: "1595428774223-ef52624120d2", blurb: "Corner shelves and bookcases that turn unused corners into storage and display space.", features: ["Fits snugly into corners","Floating or standing options","Sturdy shelf boards","Wall-anchoring hardware"], specs: {"Material":"MDF / metal","Finish":"Black / oak / walnut","Mounting":"Wall / floor"}, colors: ["Black","Oak","Walnut"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862161/products/gks8d5cw8wvn6vg0t9ii.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862161/products/kmnlwsv5cscvpsdhdlyv.jpg"] },
    ],
  },
  {
    slug: "living-room", name: "Living Room & Bedroom", short: "Living & Bedroom", image: "1618221195710-dd6b41faaea6",
    description: "Sofas, TV units, tables, beds and storage that bring comfort and order to your living room and bedroom.",
    subcategories: [
      { slug: "sofas", name: "Sofas", image: "1555041469-a586c61ea9bc", blurb: "Sofas and corner sofas in velvet, leather and classic carved-wood styles.", features: ["Hardwood frame","High-density foam seating","Multiple seating layouts","Custom fabrics on request"], specs: {"Frame":"Hardwood","Foam":"High density","Upholstery":"Velvet / leather / fabric"}, colors: ["Cream","Black","Brown","Blue"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862137/products/a2u3eo9gb37artqklayn.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862137/products/tf4gu5sc2a5nd6zh7akf.jpg"], madeToOrder: true },
      { slug: "center-tables", name: "Coffee & Center Tables", image: "1567767292278-a4f21aa2d36e", blurb: "Coffee tables with open shelves and drawers for living rooms of every size.", features: ["Handy lower shelf or drawers","Solid, level base","Wipe-clean top","Suits modern and classic rooms"], specs: {"Top":"Laminated board / wood","Storage":"Shelf / drawers","Finish":"Oak / mahogany"}, colors: ["Oak","Mahogany"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862139/products/vvufuxycj9jyb6opwxg5.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862139/products/wvd71rgaytispeodevaf.jpg"] },
      { slug: "tv-stands", name: "TV Stands", image: "1594026112284-02bb6f3352fe", blurb: "Media consoles in walnut, oak, white and black with drawers, shelves and cable routing.", features: ["Drawers and open shelves","Holds TVs up to 65 inches","Cable management","Stable legs or plinth"], specs: {"Material":"Engineered wood","Finish":"Walnut / black / white / oak","Storage":"Drawers & shelves"}, colors: ["Walnut","Black","White","Oak"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862128/products/jcip0uwsoi2hjbo7sabc.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862129/products/wxoemi0fv6g0ceszq5px.jpg"] },
      { slug: "l-shaped-tv-units", name: "L-Shaped TV Units", image: "1600121848594-d8644e57abab", blurb: "Modular and corner TV units that double as bookcases — adjust the layout to your room.", features: ["Modular, rearrangeable layout","Doubles as a bookcase","Open cubbies for decor","Easy assembly"], specs: {"Material":"Engineered wood","Layout":"L-shaped / modular","Finish":"Black / white"}, colors: ["White","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862131/products/yafklcqekqxrv7lhoo0s.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862131/products/uhvgdjvvg4wmiyr2xpml.jpg"] },
      { slug: "chests-of-drawers", name: "Chests of Drawers", image: "1595515106969-1ce29566ff1c", blurb: "Clean-lined three and six-drawer chests and dressers for bedrooms and hallways.", features: ["Smooth-running drawers","Deep storage","Cut-out handles","Wide and compact sizes"], specs: {"Material":"Engineered wood","Drawers":"3 / 6","Finish":"White / black / walnut"}, colors: ["White","Walnut","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862167/products/hxyci5kczml0usx3mtxa.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862167/products/mybmrnvcc2x59hatquey.jpg"] },
      { slug: "book-shelves", name: "Bookshelves", image: "1521587760476-6c12a4b040da", blurb: "Tree, ladder and cube bookshelves to show off books and decor.", features: ["Open shelving","Stable, anti-tip design","Space-saving footprints","Wall-anchoring kit"], specs: {"Material":"Engineered wood / metal","Finish":"Walnut / black / white"}, colors: ["White","Walnut","Mahogany","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862127/products/mk7qzdtpbrrfkccjevqa.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862127/products/qckhcvrm9oi7wfqbruyj.jpg"] },
      { slug: "wall-shelves", name: "Wall Shelves", image: "1568667256549-094345857637", blurb: "Floating, interlocking and rope-hung wall shelves for books, plants and photo frames.", features: ["Wall-mounted","Easy to install","Display plants and decor","Hanging and floating styles"], specs: {"Material":"Wood / MDF / rope","Finish":"Black / walnut / white","Mounting":"Wall"}, colors: ["Black","Walnut","Oak","Teak"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862135/products/wzow6y2x6z5y1grckbmg.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862136/products/notfliimncx4nka3anhi.jpg"] },
      { slug: "shoe-racks", name: "Shoe Racks & Benches", image: "1556020685-ae41abfc9365", blurb: "Shoe racks and storage benches that keep the entryway tidy.", features: ["Holds many pairs","Cushioned seat on bench models","Flip-down or open shelves","Slim, entryway-friendly size"], specs: {"Material":"Engineered wood / metal","Capacity":"8 – 20 pairs","Finish":"Teak / white / black"}, colors: ["White","Teak"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862134/products/ezqjjhqahywnoytwuaey.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862134/products/tgxcye7mlc5mwtk1hahp.jpg"] },
      { slug: "bedside-tables", name: "Side & Bedside Tables", image: "1522771739844-6a9f6d5f14af", blurb: "Two-tier side tables with metal frames for beds, sofas and corners.", features: ["Compact two-tier design","Sturdy metal frame","Handy lower shelf","Easy assembly"], specs: {"Top":"Laminated board","Frame":"Powder-coated steel","Finish":"Walnut / white"}, colors: ["Walnut","Black","White"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862123/products/gotu5tstxfpuqqiwwy78.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862124/products/ebc2om5hddlhbhbyxvr6.jpg"] },
      { slug: "double-beds", name: "Double Beds", image: "1540518614846-7eded433c457", blurb: "Upholstered, wooden and metal double beds, available with matching dressers and side tables.", features: ["Solid slatted base","Upholstered or wooden headboards","Storage options","Mattress sold separately"], specs: {"Frame":"Solid wood / metal","Headboard":"Upholstered / wooden","Size":"Queen / King"}, colors: ["Teak","Oak","Walnut","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862124/products/ik888otscim3eqckxnxx.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862125/products/kj0rz09wapijyuwbq65t.jpg"], madeToOrder: true },
      { slug: "single-beds", name: "Single Beds", image: "1505693416388-ac5ce068fe85", blurb: "Single beds in teak, walnut and upholstered finishes — some with storage drawers.", features: ["Strong slatted base","Storage drawer options","Matching side tables","Mattress sold separately"], specs: {"Frame":"Wood / upholstered","Storage":"Drawers / hydraulic","Size":"Single"}, colors: ["Teak","Walnut","Grey","White"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862126/products/q3ip8vtabaql9ozriftj.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862126/products/rstfmarbgeavshi9fb0i.jpg"], madeToOrder: true },
      { slug: "bedroom-chairs", name: "Accent & Bedroom Chairs", image: "1586023492125-27b2c045efd7", blurb: "Velvet, tufted and carved accent chairs for bedrooms, lounges and dressing corners.", features: ["Plush velvet or leather","Statement frames","Comfortable foam seats","Pairs and single chairs"], specs: {"Frame":"Hardwood / metal","Upholstery":"Velvet / leather"}, colors: ["Grey","Black","Tan"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862122/products/fkdcgg4bnsbeibvre6av.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862122/products/jbmyaqnlvxaoyde3ki8u.jpg"] },
    ],
  },
  {
    slug: "beanbags", name: "Bean Bags", short: "Bean Bags", image: "1493663284031-b7e3aefcae8e",
    description: "Bean bags, loungers and poufs for kids and adults — comfortable, easy to clean and fully refillable.",
    subcategories: [
      { slug: "adult-beanbags", name: "Adult Bean Bags", image: "1524758631624-e2822e304c36", blurb: "Oversized bean bags, loungers and matching poufs in leatherette and fabric.", features: ["Water-resistant leatherette or soft fabric","Double-stitched seams with zipper","Premium bead filling","Refillable"], specs: {"Cover":"Leatherette / fabric","Filling":"EPS beads","Sizes":"Medium – Jumbo","Care":"Wipe clean"}, colors: ["Red","Black","Blue","Navy"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862115/products/yoh6nqibchjqum9myupf.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862115/products/ggxzssg8xhro7xqxgkbd.jpg"] },
      { slug: "kids-beanbags", name: "Kids Bean Bags", image: "1616594039964-ae9021a400a0", blurb: "Fun cartoon-print bean bag sofas and seats sized just right for children.", features: ["Soft, child-friendly covers","Bright cartoon prints","Light enough for kids to move","Secure zipper"], specs: {"Cover":"Printed fabric / leatherette","Filling":"EPS beads","Age":"2 – 10 years","Care":"Wipe clean"}, colors: ["Orange","Yellow","Black","Red"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862117/products/fy7z5nufl0ijbw3s0wri.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862117/products/iuzcmifk8sht8qrv9t0r.jpg"] },
    ],
  },
  {
    slug: "cafe", name: "Café & Restaurant", short: "Café", image: "1554118811-1e0d58224f24",
    description: "Café chairs, tables and bar stools for restaurants, cafés and food courts.",
    subcategories: [
      { slug: "cafe-chairs", name: "Café Chairs", image: "1592078615290-033ee584e267", blurb: "Metal, moulded and upholstered chairs for busy cafés and restaurants.", features: ["Strong frames for daily use","Easy-clean finishes","Stylish retro and modern designs","Suitable for bulk orders"], specs: {"Frame":"Metal / beech wood","Seat":"Moulded / upholstered","Use":"Commercial"}, colors: ["Black","Blue","Walnut","Orange"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862120/products/yelnzes34uupvoyy3pbf.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862120/products/jpmpov1yppo72u8qbvvw.jpg"] },
      { slug: "cafe-tables", name: "Café Tables", image: "1533090481720-856c6e3c1fdc", blurb: "Round and square café tables on metal and wooden bases.", features: ["Sturdy base","Scratch-resistant tops","Round, square and rectangular","Indoor use"], specs: {"Top":"Wood / laminate","Base":"Steel / wood","Use":"Commercial"}, colors: ["Oak","Walnut","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862121/products/lglbugdd3hq3yltbakyc.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862121/products/bbcbgodrxvkxfyogpdky.jpg"] },
      { slug: "bar-stools", name: "Bar Stools", image: "1581539250439-c96689b516dd", blurb: "Adjustable and fixed-height bar stools for counters, cafés and kitchens.", features: ["Gas-lift height adjustment on select models","Footrest ring","Chrome or metal bases","Easy to clean"], specs: {"Frame":"Chrome / steel","Seat":"Leatherette / ABS / metal","Height":"Counter / bar"}, colors: ["Black","Brown","White"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862166/products/bin1cllr8v0bwemzsqa1.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862166/products/kxtdrwqm4yigzyqdkffw.jpg"] },
    ],
  },
  {
    slug: "school", name: "School Furniture", short: "School", image: "1507842217343-583bb7270b66",
    description: "Desk benches, student chairs and writing-pad chairs for schools, colleges and institutes.",
    subcategories: [
      { slug: "desk-benches", name: "Desk Benches", image: "1519974719765-e6559eac2575", blurb: "Single and double bench desks built for classrooms.", features: ["Steel frame with wooden or laminate top","Attached bench seating","Built for daily classroom use","Bulk and custom sizes"], specs: {"Top":"Wood / laminate","Frame":"Steel","Seats":"2 – 3"}, colors: ["Yellow","Blue"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862158/products/w42ifwumq8kjclypsubn.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862158/products/y58cx7tmsl2pzxibfs7g.jpg"], madeToOrder: true },
      { slug: "school-chairs", name: "School & Student Chairs", image: "1538688525198-9b88f6f53126", blurb: "Stackable student chairs and chairs with writing pads for classrooms and lecture halls.", features: ["Writing-pad options","Stackable designs","Strong steel frames","Easy-clean seats"], specs: {"Frame":"Steel","Seat":"Moulded / wooden / padded","Pad":"Optional"}, colors: ["Blue","Black"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862159/products/ch1sojseuldpzy4ksi0r.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862159/products/iidfutf2xwxezrs9jxlx.jpg"] },
    ],
  },
  {
    slug: "outdoor", name: "Outdoor Furniture", short: "Outdoor", image: "1501339847302-ac426a4a7cbb",
    description: "Garden chairs, swings and patio sets for lawns, terraces and balconies.",
    subcategories: [
      { slug: "outdoor-chairs", name: "Outdoor Chairs & Swings", image: "1577140917170-285929fb55b7", blurb: "Garden chairs, rocking chairs and hanging egg swings for lawns and balconies.", features: ["Weather-resistant frames","Comfortable cushions","Rocking and hanging styles","Easy to clean"], specs: {"Frame":"PVC / steel / rattan","Cushion":"Included","Use":"Outdoor"}, colors: ["Black","White","Red"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862134/products/q3nn5oejvvthqilkr3jj.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862156/products/uoqhqx3qcf43d6ahvo32.jpg"] },
      { slug: "outdoor-sets", name: "Outdoor Sets", image: "1505843490538-5133c6c7d0e1", blurb: "Garden sofa sets, dining sets and umbrella sets for lawns, terraces and balconies.", features: ["Weather-resistant rattan and frames","Complete sets","Comfortable cushions","Easy to clean"], specs: {"Frame":"Rattan / steel","Cushion":"Included","Use":"Outdoor"}, colors: ["Brown"], gallery: ["https://res.cloudinary.com/aepcimps/image/upload/v1790862157/products/otqcz7rvhlkmatx6evdo.jpg","https://res.cloudinary.com/aepcimps/image/upload/v1790862157/products/mcvakzyjuoqsr1y1je1u.jpg"] },
    ],
  },
];
